version: '3.6'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: abc-123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin -d postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_statement=all"]

  graphql-engine:
    image: hasura/graphql-engine:latest
    container_name: hasura
    ports:
      - "8091:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://pgadmin:abc-123@postgres:5432/northwind
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "your-admin-secret-key"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    restart: unless-stopped

volumes:
  postgres-data:
